export { authClient, usersClient } from "./auth";
export { licensingClient } from "./licensing";
export { complaintsClient } from "./complaints";
export { publicationsClient } from "./publications";
export { tendersClient } from "./tenders";
export { newsClient } from "./news";
export { analyticsClient } from "./analytics";
export { notificationsClient } from "./notifications";
export { domainsClient } from "./domains";
export { coveragesClient } from "./coverages";
export { qoeClient } from "./qoe";
export { scorecardClient } from "./scorecard";
export { alertsClient } from "./alerts";
export { cybersecurityClient } from "./cybersecurity";
